### ISSUE TITLE
Serializing an circular object to JSON causes an infinite recursion

### ISSUE THREAD

**Issue by ChayimFriedman2** [domeengine/dome#141]
Try it:
```wren
import "json" for Json

class Game {
  static init() {
    var a = []
    a.add(a)
    System.print(Json.encode(a)) // Causes an infinite recursion
  }
  static update() {}
  static draw(alpha) {}
}
```
(It is hard to observe this because Wren does nothing when an allocation fails (which is another problem) and the Wren stack is implemented using dynamic allocation, but you can see that by inspecting the process' memory consumption. It should be constant and high).

This is how the same problem is solved in other languages:
 - In JS, a circular json [throws a `TypeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Exceptions).
 - In Python, by default, a circular json [raises a `ValueError`](https://docs.python.org/3/library/json.html), but you can specify `check_circular=False` and then circles will cause an infinite recursion (and an `OverflowError`).

It seems that the right approach is to abort the fiber (or return a `JsonError`, depending on the flag `JsonOptions.abortOnError`) if a circle is found, maybe with an option to avoid this check in order to speed up serialization (like Python).

**Comment by avivbeeri** [comment]
I think that the only way to fix this is with access to some kind of object-hashing function, so we can check for prior visitation.

Not sure about alternative fixes or workarounds at this time, except "_don't do it"_.

**Comment by ChayimFriedman2** [comment]
When I will have enough free time I will check what others do.

**Comment by ChayimFriedman2** [comment]
It turns out that:

 - Python uses a map and stores the object IDs `id(obj)` inside. I don't know why the use a map and not a set. As you said, we can't implement that until we have some form of the Python's `id()` function.
 - V8 implement this using a simple stack. This sound like too slow to me, but since that's V8 (not some anonymous Wren implementation... 😜) I tend to think they know what they do, particularly because JSON is quite fundamental in JS. Maybe they checked and discovered that JSON structures tend to not be deep, and so using a hash map will be a waste. I don't know, but I fell quite comfortable to do the same (we can compare using `Object.same(_,_)`).

**Comment by avivbeeri** [comment]
We could do it python's way, with an internal ID tag, although we would need to use some kind of reserved id value for that, which is not ideal.

We would have to strip it again after the function is called.

**Comment by ChayimFriedman2** [comment]
But how will you tag a map? I feel it's better to do it the V8's way.

**Comment by avivbeeri** [comment]
Ah, I didn't realise we actually had an `Object.same` implementation available. That works.
