### ISSUE TITLE
Font metaclass does not implement 'load(_,_)'

### ISSUE THREAD

**Issue by BenStigsen** [domeengine/dome#160]
I'm not able to load a font to use for drawing. I'm not too experienced with Wren, but these are the things I've tried to load the font in the same directory as the game:
- `Font.load("monogram", "./monogram.ttf")`
- `Canvas.font = "./monogram.ttf"`

This gives the error `Font metaclass does not implement 'load(_,_)'`

I'm not sure if this is me or the docs, but none of these work. I can however see that the `load()` function in font.wren is `static` (so is `unload()`). I'm guessing this makes the functions private, so I'm not able to call them?

**Comment by avivbeeri** [comment]
`static` means that they belong to the class, rather than to "instances" of the class. Every method in Wren is public.

The problem is that `load` takes three arguments, not two: The name, path and size.

You should do:
```
Font.load("monogram", "./monogram.tff", 8")
Canvas.font = "monogram"
```

**Comment by BenStigsen** [comment]
Ah, thank you. _(sorry for the unnecessary PR)_

**Comment by avivbeeri** [comment]
No worries, it's a learning process :) The issue with TTF fonts is that you need to give them some kind of size, otherwise I'd have put some kind of default there. 

(Plus, sizes aren't uniform across fonts)
