### ISSUE TITLE
[bug] Crash when loads random module and exits the game

### ISSUE THREAD

**Issue by NEKERAFA** [domeengine/dome#163]
**Describe the bug**
I use the random module to generate random points in my game, but, when the game closes, it stops abnormaly, returning the following message into the console:

```
free(): invalid next size (fast)
Abort (`core' dumped)
```

**To Reproduce**
1. Loads random module
2. Closes the window or use Process.exit()

**Platform and version**
* dome v1.5.0
* Kubuntu 20.04.1 LTS - amd64

**Comment by avivbeeri** [comment]
Thank you for reporting this. I believe I have fixed the issue. I will have to issue a hot fix build for people trying to use precompiled binaries.
