### ISSUE TITLE
Can't call arbitrary wren files via command line on Windows

### ISSUE THREAD

**Issue by avivbeeri** [domeengine/dome#172]
Trying to run `> ./dome.exe main.wren` or similar results in the error message:

```
$ ./dome.exe main.wren
Error: Could not load ▒A
```

Chances are it is related to the `chdir` call in src/main.c, but investigation required.

**Comment by ChayimFriedman2** [comment]
Hah? It works for me.

**Comment by avivbeeri** [comment]
I've found the issue, PR incoming.
