### ISSUE TITLE
`Canvas.offset` for retrieving the current offset

### ISSUE THREAD

**Issue by avivbeeri** [domeengine/dome#187]
It's impossible to retrieve the current canvas offset, making it hard to temporarily reset it.

We already have `Canvas.offset()` and `Canvas.offset(x, y)` for setting the offset, but no way to retrieve it. Perhaps a `Canvas.offset` getter (with a reciprocal setter) could provide the result as a `Vector`.

**Comment by TheKing0x9** [comment]
Will it be fine to expose `offsetX` and `offsetY` as foreign variables to Wren and then provide `offset` getter from there? Or is there a way that `Vector.new` can be called from `C`

**Comment by avivbeeri** [comment]
We probably need to do it the way the Mouse coordinates are retrieved. (https://github.com/domeengine/dome/blob/a502a220989b195d39a79bb0c34503088bd22e43/src/modules/input.wren#L110)

Separate foreign calls for X and Y, combined into a vector constructor

**Comment by TheKing0x9** [comment]
Thanks. I have fixed the issue and will submit a pr soon
