### ISSUE TITLE
Update `math` module to use new Num methods

### ISSUE THREAD

**Issue by avivbeeri** [domeengine/dome#198]
Wren 0.4.0 introduced more methods for the Num class, such as a built in `min`, `max` and `clamp`/`mid` implementation. Consult the Wren 0.4.0 release notes for a full list of added methods.

I think it would be good for DOME to defer to these implementations where available. 

We should also add `clamp` as an `alias` for `mid`.

**Comment by BenStigsen** [comment]
> I think it would be good for DOME to defer to these implementations where available.

Agreed.

> We should also add clamp as an alias for mid.

I do not think an alias is needed. I think that clamp is more descriptive where as I could imagine `mid` being confused with the average between two values.

**Comment by avivbeeri** [comment]
We already have `mid` (I named it based on the pico8 version of this method) and then Wren added `clamp`, which does exactly the same thing, so I don't see any harm in adding it as an alias, for people expecting the Wren-style to be present.

**Comment by BenStigsen** [comment]
Oh, I just thought that Wren added `clamp` for the first time, but if `mid` already exists then yeah okay, an alias would make a lot of sense.

**Comment by TheKing0x9** [comment]
Should I take up and solve this issue?

**Comment by avivbeeri** [comment]
If you feel that you want to, I'm very happy for you to do so! 

I keep issues like this open specifically for new people to contribute to the project :)

**Comment by TheKing0x9** [comment]
Great! I'll send a PR right away
