### ISSUE TITLE
Update function not having a delta time parameter

### ISSUE THREAD

**Issue by AdamVGA** [domeengine/dome#199]

**Comment by AdamVGA** [comment]
WOOPS. Accidental

**Comment by AdamVGA** [comment]
Why is that? Wouldn't it be useful to have one?

**Comment by avivbeeri** [comment]
Hi there, thank you for the issue! 

DOME is designed to use a " fixed-interval update" system, so you should always assume that `Game.update()` is called 60 times a second, representing a slice of 16.6ms. This isn't true for the `draw` call though, which is called at arbitrary times.

The reasons for this are explained in more detail here: https://domeengine.com/guides/game-loop

**Comment by DMClVG** [comment]
Okay, understood. Thanks for the quick reply!
