### ISSUE TITLE
`Canvas.font` for retrieving the current font

### ISSUE THREAD

**Issue by BenStigsen** [domeengine/dome#202]
It's impossible to retrieve the current canvas font, making it harder to do something like:
`Font[Canvas.font].getArea("Hello World!")`

It's currently possible to set `Canvas.font` so it should also be possible to retrieve the font name as a String

**Comment by avivbeeri** [comment]
This was done here: https://github.com/domeengine/dome/pull/200

It just didn't make it in the 1.6.1

**Comment by BenStigsen** [comment]
That's even the PR I made, what is wrong with me. Let's blame it on lack of sleep.
