### ISSUE TITLE
graphicsApi: Canvas does not resize after init

### ISSUE THREAD

**Issue by trelemar** [domeengine/dome#217]
https://github.com/domeengine/dome/commit/fd151ca9e32d9240bd8590aef2f37b27bd43cd82#diff-9a374d22bff4ab7df3071a77e0823291bf89a71d371570d110eb432251100cfcL1046-L1048
https://github.com/domeengine/dome/blob/980d85b48f889897e9234ffc95b195a86b93db77/src/engine.c#L1031-L1033

I'm guessing when the gif recorder was removed this chunk was left in but it causes the function to return true if the engine was initialized. So you can never resize the canvas after `init`

**Comment by avivbeeri** [comment]
Good catch! This meant that you couldn't resize the canvas after the Game.init method was called.
