### ISSUE TITLE
embed may failed on windows wsl2

### ISSUE THREAD

**Issue by dotnfc** [domeengine/dome#265]
on windows wsl2, we may use TortoiseGit to clone dome repo with CrLf, so the generated .inc files may be incorrect for '\r' char.
how about adding serveral lines to handle this in the embedlib.c:

27    if (*ptr == '\n') {
28        fputs("'\\n',", fp);
29        fputs("\n", fp);
30    } else if (*ptr == '\r') {   <<<
31        continue;              <<< 
32    } else {
33       fputs("'", fp);

**Comment by avivbeeri** [comment]
Just clarifying, you're suggesting adding lines 30 and 31 here?
