### ISSUE TITLE
Any plans to add collision detection?

### ISSUE THREAD

**Issue by avrame** [domeengine/dome#271]
Or is that out-of-scope for DOME?

**Comment by avivbeeri** [comment]
I have considered adding collision detection in the future. It sits on a higher level of logic than DOME currently provides, along with some notion of "game entity" and other facilities.

Collision detection is also dependant on the "physics" of your game. Very simple grid based games might have a different idea of what it means to be colliding, compared to a more real time action experience.

What it means is that (a) I don't know if it's something DOME _should_ provide, or leave it to the developer to place themselves and (b) If I do want to add it, it needs to fit into the bigger picture, which is also on the table for design.

I have _some_ thoughts around how I like to architect my games and entities, but I don't know if it works for all kinds of games or just the ones I've made recently. I've only been making turn-based dungeon crawlers for the last couple years, which come with some interesting requirements.

For now, DOME is a solid foundation for most things you might want to build, but it is very much Bring-Your-Own.

**Comment by avrame** [comment]
That makes sense, thanks for answering!
