### ISSUE TITLE
fps reduced when adding to many item in list

### ISSUE THREAD

**Issue by ghost** [domeengine/dome#272]
fps reduced when adding to many item in list
with 0 vector in list (image 1) : 
![screenshot - Copy](https://github.com/domeengine/dome/assets/162813353/711841a4-7b2d-4df3-8da0-dc10fad69dc6)
with 1000 vector in list (image 2) : 
![screenshot](https://github.com/domeengine/dome/assets/162813353/46aa5e55-41a8-4e86-9851-ac9b13e2cba1)
(fps reduced by 40 percent)

**Comment by avivbeeri** [comment]
Hi there,

Because Wren code is running in a virtual machine you need to be careful
what you do in draw and update steps of the game loop to optimise
performance.

Without full context, I can't advise you on next steps, but this isn't
really a bug or an issue with DOME.
